### ISSUE TITLE
ChromeCastButton not showing

### ISSUE THREAD

**Issue by snorreks** [PalaTeam/flutter_video_cast#6]
The casting button is not visible or clickable. 

Flutter: stable, 1.22.5
flutter_video_cast: 1.0.3
Tested on a real device Huwaii mrd lx1

How I configured the ChromeCastButton:
```dart
        ChromeCastButton(
            key: const Key('cast-button'),
            color: Colors.orange,
            size: 50,
            onButtonCreated: (ChromeCastController controller) {},
            onRequestCompleted: () {},
            onRequestFailed: (String error) {},
            onSessionEnded: () {},
            onSessionStarted: () {},
          ),
```
The output in the flutter dev tools:
![image](https://user-images.githubusercontent.com/36089469/105721668-20950d80-5f25-11eb-9a97-2c8469a4bed4.png)

**Comment by ruandutrab** [comment]
Hi, how are you? You modified in "\flutter_video_cast-master\example\android\app\src\main\kotlin\it\aesys\flutter_video_cast_example". 
file name: MainActivity.kt

**Comment by anup-geeky** [comment]
@snorreks @ruandutrab any solution?

**Comment by HiteshPrajapati95** [comment]
Hello @ruandutrab @snorreks , It works for android but not for iOS app. do you have any solution?

**Comment by snorreks** [comment]
I have moved on to another packaged that works on both android and ios: https://pub.dev/packages/cast
